export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_RECIPE = "ADD_RECIPE";
export const ADD_RECIPE_ERROR = "ADD_RECIPE_ERROR";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const GET_RECIPE="GET_RECIPE";
export const GET_RECIPE_ERROR="GET_RECIPE_ERROR";
export const GET_ALL_RECIPE="GET_ALL_RECIPE";
export const LIKE_RECIPE="LIKE_RECIPE";
export const LIKE_ERROR="LIKE_ERROR";
export const GET_RECIPE_LIKES="GET_RECIPE_LIKES";
export const GET_LIKES_RECIPE_ERROR="GET_LIKES_RECIPE_ERROR";

